### ISSUE TITLE
Resume button isn't working

### ISSUE THREAD

**Issue by NathanJiangCS** [ntaocui/ntaocui.github.io#1]
### Description
The resume button in the navbar isn't working. 

### Expected Behaviour
Redirects to or opens a new tab with the resume

😭 *who is this guy?*

**Comment by sas5580** [comment]
HI, MY NAME IS ALEX BUT MY CHINESE NAME IS NAITAO BUT I RESPOND TO EITHER! I CURRENTLY ATTEND THE UNIVERSITY OF WATERLOO AS A CANDIDATE FOR THE BACHELOR OF MECHATRONICS ENGINEERING (CURRENTLY IN MY 2A TERM). IF YOU DON'T ALREADY KNOW, MECHATRONICS IS THE CHILD OF SOFTWARE, ELECTRICAL AND MECHANICAL ENGINEERING. PERHAPS BY DEFAULT, I HAVE DEVELOPED A DEEP INTEREST IN DESIGNING AND CREATING ROBOTS.

**Comment by ntaocui** [comment]
Resolved !!!
